### ISSUE TITLE
role of info and category to clarify

### ISSUE THREAD

**Issue by parguel** [FRBCesab/popbayes#5]
Is info used to carry the info about some species provided with the package?
If so, may it be modified by the user?
If not, info is provided by the user and should take precedence on info in the package itself. 
info is just a more convenient way to bring information that is situated at the species level and would otherwise appear on several rows in a count series?

In case the user can provide only some info on some species, this should be possible.

A column "category" should be allowed for a new species for which there is no more detailed info.

**Comment by ahasverus** [comment]
The vignette popabyes.Rmd explains the use of the `info` dataset: https://frbcesab.github.io/popbayes/articles/popbayes.html#the-garamba-dataset (section **_Counts conversion_**).
